colours = [
{'en': 'What colour is it?', 'uk': 'Який це колір?', 'nd': 'Welke kleur is het?'},
{'en': 'white', 'uk': 'білий', 'nd': 'wit'}, 
{'en': 'yellow', 'uk': 'жовтий', 'nd': 'geel'}, 
{'en': 'orange', 'uk': ('помаранчевий', 'жовтогарячий'), 'nd': 'oranje'}, 
{'en': 'pink', 'uk': 'рожевий', 'nd': 'roze'}, 
{'en': 'red', 'uk': 'червоний', 'nd': 'rood'}, 
{'en': 'brown', 'uk': 'коричневий', 'nd': 'bruin'}, 
{'en': 'green', 'uk': 'зелений', 'nd': 'groen'}, 
{'en': 'blue', 'uk': 'блакитний', 'nd': 'blauw'}, 
{'en': 'purple', 'uk': 'фіолетовий', 'nd': 'paars'}, 
{'en': ('grey','gray'), 'uk': 'сірий', 'nd': 'grijs'}, 
{'en': 'black', 'uk': 'чорний', 'nd': 'zwart'},
{'en': ('silver', 'silver-coloured'), 'uk': 'срібний', 'nd': ('zilveren', 'zilverkleurig')}, 
{'en': ('gold', 'gold-coloured'), 'uk': 'золотий', 'nd': ('gouden', 'goudkleurig')},
{'en': 'multicoloured', 'uk': 'різнокольоровий', 'nd': 'veelkleurig'},
{'en': 'light brown', 'uk': 'світло-коричневий', 'nd': 'lichtbruin'}, 
{'en': 'light green', 'uk': 'світло-зелений', 'nd': 'lichtgroen'}, 
{'en': 'light blue', 'uk': 'світло-блакитний', 'nd': 'lichtblauw'},
{'en': 'dark brown', 'uk': 'темно-коричневий', 'nd': 'donkerbruin'}, 
{'en': 'dark green', 'uk': 'темно-зелений', 'nd': 'donkergroen'}, 
{'en': 'dark blue', 'uk': 'синій', 'nd': 'donkerblauw'},
{'en': 'bright red', 'uk': 'яскраво-червоний', 'nd': 'felrood'}, 
{'en': 'bright green', 'uk': 'яскраво-зелений', 'nd': 'felgroen'}, 
{'en': 'bright blue', 'uk': 'яскраво-синій', 'nd': 'helderblauw'},
]