family = [
{'en': ('father', 'dad'), 'uk': ('отець', 'батько'), 'nd': 'vader'},
{'en': ('mother', 'mum'), 'uk': ('матір', 'мати'), 'nd': 'moeder'},
{'en': 'son', 'uk': 'син', 'nd': 'zoon'},
{'en': 'daughter', 'uk': 'дочка', 'nd': 'dochter'},
{'en': 'parent', 'uk': 'один з батьків', 'nd': 'ouder'},
{'en': 'child', 'uk': 'дитина', 'nd': 'kind'},
{'en': 'husband', 'uk': 'чоловік', 'nd': ('echtgenoot', 'man')},
{'en': 'wife', 'uk': ('жінка', 'дружина'), 'nd': ('echtgenote', 'vrouw')},
{'en': 'brother', 'uk': 'брат', 'nd': 'broer'},
{'en': 'sister', 'uk': 'сестра', 'nd': ('zus', 'zuster')},
{'en': 'uncle', 'uk': 'дядько', 'nd': 'oom'},
{'en': 'aunt', 'uk': 'тітка', 'nd': 'tante'},
{'en': 'nephew', 'uk': 'племінник', 'nd': 'neef'},
{'en': 'niece', 'uk': 'племінниця', 'nd': 'nicht'},
{'en': 'cousin', 'uk': ('кузен', 'кузина'), 'nd': ('neef', 'nicht')},
{'en': ('grandmother', 'granny', 'grandma'), 'uk': 'бабуся', 'nd': ('grootmoeder', 'oma')},
{'en': ('grandfather', 'granddad', 'grandpa'), 'uk': 'дідусь', 'nd': ('grootvader', 'opa')},
{'en': 'grandparents', 'uk': 'дідусь та бабуся', 'nd': 'grootouders'},
{'en': 'grandson', 'uk': 'онук', 'nd': 'kleinzoon'},
{'en': 'granddaughter', 'uk': 'онучка', 'nd': 'kleindochter'},
{'en': 'grandchild', 'uk': ('онук', 'онучка'), 'nd': 'kleinkind'},

{'en': 'boyfriend', 'uk': 'хлопець', 'nd': 'vriendje'},
{'en': 'girlfriend', 'uk': 'дівчина', 'nd': 'vriendin'},
{'en': 'partner', 'uk': 'партнер', 'nd': 'partner'},
{'en': ('fiancé', 'groom', 'bridegroom'), 'uk': ('наречений', 'молодий'), 'nd': ('verloofde', 'bruidegom')},
{'en': ('fiancée', 'bride'), 'uk': ('наречена', 'молода'), 'nd': ('bruid', 'verloofde')},

{'en': 'godfather', 'uk': 'хрещений', 'nd': ('peetvader', 'peter')},
{'en': 'godmother', 'uk': 'хрещена', 'nd': 'meter'},
{'en': 'godson', 'uk': 'хрещений син', 'nd': 'peetzoon'},
{'en': 'goddaughter', 'uk': 'хрещена дочка', 'nd': 'peetdochter'},
{'en': 'stepfather', 'uk': 'вітчим', 'nd': 'stiefvader'},
{'en': 'stepmother', 'uk': 'мачуха', 'nd': 'stiefmoeder'},
{'en': 'stepson', 'uk': 'пасинок', 'nd': 'stiefzoon'},
{'en': 'stepdaughter', 'uk': 'пасербиця', 'nd': 'stiefdochter'},
{'en': 'stepbrother', 'uk': 'зведений брат', 'nd': 'stiefbroer'},
{'en': 'stepsister', 'uk': 'зведена сестра', 'nd': 'stiefzuster'},
{'en': 'half-sister', 'uk': 'сестра по одному з батьків', 'nd': 'halfzus'},
{'en': 'half-brother', 'uk': 'брат по одному з батьків', 'nd': 'halfbroer'},

{'en': 'mother-in-law', 'uk': ('теща', 'свекруха'), 'nd': 'schoonmoeder'},
{'en': 'father-in-law', 'uk': ('тесть', 'свекор'), 'nd': 'schoonvader'},
{'en': 'son-in-law', 'uk': 'зять', 'nd': 'schoonzoon'},
{'en': 'daughter-in-law', 'uk': 'невістка', 'nd': 'schoondochter'},
{'en': 'sister-in-law', 'uk': ('невістка (дружина брата)', 'зовиця (сестра чоловіка)', 'своячка (сестра дружини)'), 'nd': 'schoonzuster'},
{'en': 'brother-in-law', 'uk': ('зять (чоловік сестри)', 'шурин (брат дружини)', 'свояк (чоловік своячки)', 'дівер (брат чоловіка)'), 'nd': ('zwager', 'schoonbroer')},

{'en': ('relation', 'relative'), 'uk': ('родич', 'родичка'), 'nd': ('familielid', 'relatief')},
{'en': 'twin', 'uk': 'близнюк', 'nd': 'tweeling'},
 
{'en': 'to be born', 'uk': 'народитися', 'nd': 'geboren worden'},
{'en': 'to die', 'uk': 'померти', 'nd': 'sterven'},

{'en': 'to get married', 'uk': 'одружитися', 'nd': ('trouwen', 'huwen')}, 
{'en': 'to get divorced', 'uk': 'розлучитись', 'nd': 'scheiden'},
 
{'en': 'to adopt', 'uk': ('удочерити', 'усиновити'), 'nd': 'adopteren'},
{'en': 'adoption', 'uk': ('удочеріння', 'усиновлення'), 'nd': 'adoptie'},
{'en': 'adopted', 'uk': ('удочерена', 'усиновлений'), 'nd': 'geadopteerd'},

{'en': 'only child', 'uk': 'єдина дитина', 'nd': 'enige kind'},
{'en': 'single parent', 'uk': 'самотня матір або самотній батько', 'nd': 'alleenstaande ouder'}, 
{'en': 'single mother', 'uk': 'самотня матір', 'nd': 'alleenstaande moeder'},

{'en': 'infant', 'uk': 'немовля', 'nd': 'zuigeling'},
{'en': 'baby', 'uk': 'малюк', 'nd': 'baby'},
{'en': 'toddler', 'uk': 'дитина, що починає ходити', 'nd': 'peuter'},

{'en': 'single', 'uk': ('самотній', 'самотня'), 'nd': ('single', 'alleenstaand')},
{'en': 'engaged', 'uk': ('заручений', 'заручена'), 'nd': 'verloofd'},
{'en': 'married', 'uk': ('одружений', 'заміжня'), 'nd': ('getrouwd', 'gehuwd')},
{'en': ('divorced', 'separated'), 'uk': ('розлучений', 'розлучена'), 'nd': 'gescheiden'},
{'en': 'widow', 'uk': 'вдова', 'nd': 'weduwe'},
{'en': 'widower', 'uk': 'вдівець', 'nd': 'weduwnaar'},

{'en': 'marriage', 'uk': 'шлюб', 'nd': 'huwelijk'},
{'en': 'wedding', 'uk': 'весілля', 'nd': 'bruiloft'},

{'en': 'best man', 'uk': 'дружок', 'nd': 'bruidsjonker'},
{'en': 'bridesmaid', 'uk': 'дружка', 'nd': 'bruidsmeisje'},
 
{'en': 'wedding day', 'uk': 'день весілля', 'nd': 'trouwdag'},
{'en': 'wedding ring', 'uk': 'обручка', 'nd': 'trouwring'},
{'en': 'wedding cake', 'uk': 'весільний торт', 'nd': 'bruidstaart'},
{'en': 'wedding dress', 'uk': 'весільна сукня', 'nd': 'trouwjurk'},

{'en': 'honeymoon', 'uk': 'медовий місяць', 'nd': 'huwelijksreis'},
{'en': ('anniversary', 'wedding anniversary'), 'uk': 'річниця весілля', 'nd': 'trouwdag'},
]