ttime = [
{'en': 'second', 'uk': 'секунда', 'nd': 'seconde'},
{'en': 'minute', 'uk': 'хвилина', 'nd': 'minuut'},
{'en': 'hour', 'uk': 'година', 'nd': 'uur'},
{'en': 'day', 'uk': 'день', 'nd': 'dag'},
{'en': 'week', 'uk': 'тиждень', 'nd': 'week'},
{'en': 'fortnight', 'uk': 'два тижні', 'nd': 'twee weken'},
{'en': 'month', 'uk': 'місяць', 'nd': 'maand'},
{'en': 'year', 'uk': 'рік', 'nd': 'jaar'},
{'en': 'decade', 'uk': 'десятиліття', 'nd': 'decennium'},
{'en': 'century', 'uk': 'століття', 'nd':'eeuw'},
{'en': 'weekend', 'uk': 'уїк-енд, вихідні', 'nd': 'weekend'},
{'en': 'leap year', 'uk': 'високосний рік', 'nd': 'schrikkeljaar'},
{'en': 'morning', 'uk': 'ранок', 'nd': 'ochtend'},
{'en': 'afternoon', 'uk': 'час після полудня', 'nd': 'middag'},
{'en': 'evening', 'uk': 'вечір', 'nd': 'avond'},
{'en': ('night', 'night time'), 'uk': 'ніч', 'nd': 'nacht'},
{'en': ('midday', 'noon'), 'uk': 'полудень', 'nd': 'middag'},
{'en': 'midnight', 'uk': 'полуніч', 'nd': 'middernacht'},
{'en': 'dawn', 'uk': 'світанок', 'nd': 'ochtendgloren'},
{'en': 'dusk', 'uk': 'присмерк', 'nd': 'schemering'},
{'en': 'sunrise', 'uk': 'ранкова зоря', 'nd': 'zonsopkomst'},
{'en': 'sunset', 'uk': 'захiд сонця', 'nd': 'zonsondergang'},
{'en': 'now', 'uk': 'тепер', 'nd': 'nu'},
{'en': 'then', 'uk': 'тоді', 'nd': 'dan'},
{'en': ('immediately', 'straight away'), 'uk': 'негайно', 'nd': ('onmiddellijk', 'direct')},
{'en': 'soon', 'uk': 'незабаром', 'nd': 'spoedig'},
{'en': 'earlier', 'uk': 'раніше', 'nd': 'eerder'},
{'en': 'later', 'uk': 'пiзнiше', 'nd': 'later'},
{'en': 'never', 'uk': 'ніколи', 'nd': 'nooit'},
{'en': 'rarely', 'uk': 'рідко', 'nd': 'zelden'},
{'en': 'occasionally', 'uk': 'час від часу', 'nd': 'af en toe'},
{'en': 'sometimes', 'uk': 'іноді', 'nd': 'soms'},
{'en': ('often', 'frequently'), 'uk': 'часто', 'nd': 'vaak'},
{'en': ('usually', 'normally'), 'uk': 'зазвичай', 'nd': 'gebruikelijk'},
{'en': 'always', 'uk': 'завжди', 'nd': 'altijd'},
{'en': ('every day', 'daily'), 'uk': 'кожного дня', 'nd': ('elke dag', 'dagelijks')},
{'en': ('every week', 'weekly'), 'uk': 'кожного тижня', 'nd': ('elke week', 'wekelijks')},
{'en': ('every month', 'monthly'), 'uk': 'кожного місяця', 'nd': ('elke maand', 'maandelijks')},
{'en': ('every year', 'yearly'), 'uk': 'кожного року', 'nd': ('elk jaar', 'jaarlijks')},
]