weather = ['Weather',
{'en': 'sun', 'uk': 'сонце', 'nd': 'zon'},
{'en': 'sunshine', 'uk': 'сонячне сяйво', 'nd': 'zonneschijn'},
{'en': 'rain', 'uk': 'дощ', 'nd': 'regen'},
{'en': 'snow', 'uk': 'сніг', 'nd': 'sneeuw'},
{'en': 'hail', 'uk': 'град', 'nd': 'hagel'},
{'en': 'drizzle', 'uk': ('мжичка', 'мряка'), 'nd': 'motregen'},
{'en': 'sleet', 'uk': 'мокрий сніг', 'nd': 'natte sneeuw'},
{'en': 'shower', 'uk': 'злива', 'nd': 'douche'},
{'en': 'mist', 'uk': 'легкий туман', 'nd': 'nevel'},
{'en': 'fog', 'uk': 'туман', 'nd': 'mist'},
{'en': 'cloud', 'uk': 'хмара', 'nd': 'wolk'},
{'en': 'rainbow', 'uk': 'веселка', 'nd': 'regenboog'},
{'en': 'wind', 'uk': 'вітер', 'nd': 'wind'},
{'en': 'breeze', 'uk': 'легкий вітер', 'nd': 'bries'},
{'en': 'strong winds', 'uk': 'сильний вітер', 'nd': 'harde wind'},
{'en': 'thunder', 'uk': 'грім', 'nd': 'donder'},
{'en': 'lightning', 'uk': 'блискавка', 'nd': 'bliksem'},
{'en': 'storm', 'uk': 'шторм', 'nd': ('storm', 'onweer')},
{'en': 'thunderstorm', 'uk': 'гроза', 'nd': 'onweersbui'},
{'en': 'gale', 'uk': ('шторм', 'буревій'), 'nd': ('storm', 'gagel')},
{'en': 'tornado', 'uk': 'торнадо', 'nd': 'tornado'},
{'en': 'hurricane', 'uk': 'ураган', 'nd': 'orkaan'},
{'en': 'flood', 'uk': 'повінь', 'nd': 'overstroming'},
{'en': 'frost', 'uk': 'мороз', 'nd': 'vorst'},
{'en': 'ice', 'uk': 'лід', 'nd': 'ijs'},
{'en': 'drought', 'uk': 'посуха', 'nd': 'droogte'},
{'en': 'heatwave', 'uk': 'спека', 'nd': 'hittegolf'},
{'en': 'windy', 'uk': 'вітряно', 'nd': 'winderig'},
{'en': 'cloudy', 'uk': 'хмарно', 'nd': 'bewolkt'},
{'en': 'foggy', 'uk': 'туманно', 'nd': 'mistig'},
{'en': 'misty', 'uk': 'мрячнo', 'nd': 'nevelig'},
{'en': 'icy', 'uk': 'крижаний', 'nd': 'ijzig'},
{'en': 'frosty', 'uk': 'морознo', 'nd': 'vorstig'},
{'en': 'stormy', 'uk': 'штормить', 'nd': 'stormachtig'},
{'en': 'dry', 'uk': 'сухo', 'nd': 'droog'},
{'en': 'wet', 'uk': 'мокро', 'nd': 'nat'},
{'en': 'hot', 'uk': 'спекотно', 'nd': 'heet'},
{'en': 'cold', 'uk': 'холоднo', 'nd': 'koud'},
{'en': 'chilly', 'uk': 'прохолоднo', 'nd': 'kil'},
{'en': 'sunny', 'uk': 'сонячнo', 'nd': 'zonnig'},
{'en': 'rainy', 'uk': 'дощить', 'nd': 'regenachtig'},
{'en': 'fine', 'uk': 'гарно', 'nd': 'prima'},
{'en': 'dull', 'uk': 'похмурo', 'nd': 'somber'},
{'en': 'overcast', 'uk': 'хмарно', 'nd': 'bewolkt'},
{'en': 'humid', 'uk': 'вологo', 'nd': 'vochtig'},

{'en': 'raindrop', 'uk': 'крапля дощу', 'nd': 'regendruppel'},
{'en': 'snowflake', 'uk': 'сніжинка', 'nd': 'sneeuwvlok'},
{'en': 'hailstone', 'uk': 'градина', 'nd': 'hagelsteen'},
{'en': 'to melt', 'uk': 'танути', 'nd': 'smelten'},
{'en': 'to freeze', 'uk': 'замерзати', 'nd': 'bevriezen'},
{'en': 'to thaw', 'uk': 'відтавати', 'nd': 'ontdooien'},
{'en': 'to snow', 'uk': 'йти (про сніг)', 'nd': 'sneeuwen'},
{'en': 'to rain', 'uk': 'йти (про дощ)', 'nd': 'regenen'},
{'en': 'to hail', 'uk': 'йти (про град)', 'nd': 'hagelen'},
{'en': 'weather forecast', 'uk': 'прогноз погоди', 'nd': ('weervoorspelling', 'weerbericht')},
{'en': 'rainfall', 'uk': 'злива', 'nd': 'regenval'},
{'en': 'temperature', 'uk': 'температура', 'nd': 'temperatuur'},
{'en': 'humidity', 'uk': 'вологість', 'nd': 'vochtigheid'},
{'en': 'thermometer', 'uk': 'термометр', 'nd': 'thermometer'},
{'en': 'high pressure', 'uk': 'високий тиск', 'nd': 'hoge druk'},
{'en': 'low pressure', 'uk': 'низький тиск', 'nd': 'lage druk'},
{'en': 'barometer', 'uk': 'барометр', 'nd': 'barometer'},
{'en': 'degree', 'uk': 'градус', 'nd': 'graad'},
{'en': 'Celsius', 'uk': 'Цельсій', 'nd': 'Celsius'},
{'en': 'Fahrenheit', 'uk': 'Фаренгейт', 'nd': 'Fahrenheit'},
{'en': 'climate', 'uk': 'клімат', 'nd': 'klimaat'},
{'en': 'climate change', 'uk': 'кліматичні зміни', 'nd': 'klimaatverandering'},
{'en': 'global warming', 'uk': 'глобальне потепління', 'nd': 'opwarming van de aarde'},
]