adjective = ['Adjective',
	{'uk': 'великий', 'en': 'big', 'nd': 'groot'},
	{'uk': 'маленький', 'en': ('small', 'little'), 'nd': 'klein'},
	{'uk': 'швидкий', 'en': 'fast', 'nd': 'snel'},
	{'uk': 'повільний', 'en': 'slow', 'nd': ('langzaam', 'traag')},
	{'uk': 'добрий', 'en': 'good', 'nd': 'goed'},
	{'uk': 'поганий', 'en': 'bad', 'nd': 'slecht'},
	{'uk': 'дорогий', 'en': 'expensive', 'nd': 'duur'},
	{'uk': 'дешевий', 'en': 'cheap', 'nd': 'goedkoop'},
	{'uk': 'товстий', 'en': 'thick', 'nd': 'dik'},
	{'uk': ('тонкий', 'худий'), 'en': 'thin', 'nd': 'dun'},
	{'uk': 'вузький', 'en': 'narrow', 'nd': 'smal'},
	{'uk': 'широкий', 'en': 'wide', 'nd': 'breed'},
	{'uk': ('широкий', 'повний'), 'en': 'broad', 'nd': 'breed'},
	{'uk': 'голосний', 'en': 'loud', 'nd': 'luid'},
	{'uk': 'тихий', 'en': 'quiet', 'nd': 'rustig'},
	{'uk': 'розумний', 'en': 'intelligent', 'nd': 'intelligent'},
	{'uk': 'дурний', 'en': 'stupid', 'nd': 'dom'},
	{'uk': 'вологий', 'en': 'wet', 'nd': 'nat'},
	{'uk': 'сухий', 'en': 'dry', 'nd': 'droog'},
	{'uk': 'важкий', 'en': 'heavy', 'nd': 'zwaar'},
	{'uk': 'легкий', 'en': 'light', 'nd': 'licht'},
	{'uk': 'жорсткий', 'en': 'hard', 'nd': 'hard'},
	{'uk': "м'який", 'en': 'soft', 'nd': 'zacht'},
	{'uk': 'мілкий', 'en': 'shallow', 'nd': 'oppervlakkig'},
	{'uk': 'глибокий', 'en': 'deep', 'nd': 'diep'},
	{'uk': 'простий', 'en': 'easy', 'nd': 'makkelijk'},
	{'uk': 'складний', 'en': 'difficult', 'nd': 'moeilijk'},
	{'uk': 'слабкий', 'en': 'weak', 'nd': 'zwak'},
	{'uk': 'сильний', 'en': 'strong', 'nd': 'sterk'},
	{'uk': 'багатий', 'en': 'rich', 'nd': 'rijk'},
	{'uk': 'бідний', 'en': 'poor', 'nd': 'arm'},
	{'uk': 'молодий', 'en': 'young', 'nd': 'jong'},
	{'uk': 'старий', 'en': 'old', 'nd': 'oud'},
	{'uk': 'довгий', 'en': 'long', 'nd': 'lang'},
	{'uk': 'короткий', 'en': 'short', 'nd': 'kort'},
	{'uk': 'високий', 'en': 'high', 'nd': 'hoog'},
	{'uk': 'низький', 'en': 'low', 'nd': 'laag'},
	{'uk': 'щедрий', 'en': 'generous', 'nd': 'genereus'},
	{'uk': 'грубий', 'en': 'rude', 'nd': 'brutaal'},
	{'uk': 'красивий', 'en': 'beautiful', 'nd': 'mooi'},
	{'uk': 'потворний', 'en': 'ugly', 'nd': 'lelijk'},
	{'uk': 'новий', 'en': 'new', 'nd': 'nieuw'},
	{'uk': 'щасливий', 'en': 'happy', 'nd': 'gelukkig'},
	{'uk': 'сумний', 'en': 'sad', 'nd': 'verdrietig'},
	{'uk': 'безпечний', 'en': 'safe', 'nd': 'veilig'},
	{'uk': 'небезпечний', 'en': 'dangerous', 'nd': 'gevaarlijk'},
	{'uk': 'рано', 'en': 'early', 'nd': 'vroeg'},
	{'uk': 'пізно', 'en': 'late', 'nd': 'laat'},
	{'uk': 'світлий', 'en': 'light', 'nd': 'licht'},
	{'uk': 'темний', 'en': 'dark', 'nd': 'donker'},
	{'uk': 'відкритий', 'en': 'open', 'nd': 'open'},
	{'uk': ('закритий', 'зачинений'), 'en': ('closed', 'shut'), 'nd': ('gesloten', 'dicht')},
	{'uk': 'тісний', 'en': 'tight', 'nd': ('nauw','krap')},
	{'uk': ('вільний', 'пухкий'), 'en': 'loose', 'nd': 'los'},
	{'uk': 'повний', 'en': 'full', 'nd': 'vol'},
	{'uk': 'пустий', 'en': 'empty', 'nd': 'leeg'},
	{'uk': 'багато', 'en': 'many', 'nd': 'veel'},
	{'uk': 'кілька', 'en': 'few', 'nd': 'paar'},
	{'uk': 'живий', 'en': 'alive', 'nd': 'levend'},
	{'uk': 'мертвий', 'en': 'dead', 'nd': 'dood'},
	{'uk': 'гарячий', 'en': 'hot', 'nd': 'heet'},
	{'uk': 'холодний', 'en': 'cold', 'nd': 'koud'},
	{'uk': 'цікавий', 'en': 'interesting', 'nd': 'interessant'},
	{'uk': ('скучний', 'нудний'), 'en': 'boring', 'nd': 'saai'},
	{'uk': 'невдачливий', 'en': 'unlucky', 'nd': 'ongelukkig'},
	{'uk': 'важливий', 'en': 'important', 'nd': 'belangrijk'},
	{'uk': 'неважливий', 'en': 'unimportant', 'nd': 'onbelangrijk'},
	{'uk': 'правий', 'en': 'right', 'nd': 'gelijk'},
	{'uk': 'неправий', 'en': 'wrong', 'nd': ('verkeerd', 'fout')},
	{'uk': 'далеко', 'en': 'far', 'nd': 'ver'},
	{'uk': 'близько', 'en': 'near', 'nd': ('nabij', 'dichtbij', 'in de buurt')},
	{'uk': 'чистий', 'en': 'clean', 'nd': ('proper','schoon')},
	{'uk': 'брудний', 'en': 'dirty', 'nd': 'vies'},
	{'uk': 'гарний', 'en': 'nice', 'nd': ('leuk', 'aardig')},
	{'uk': 'приємний', 'en': 'pleasant', 'nd': ('prettig', 'aangenaam')},
	{'uk': 'неприємний', 'en': 'unpleasant', 'nd': 'onaangenaam'},
	{'uk': 'відмінний', 'en': 'excellent', 'nd': 'uitstekend'},
	{'uk': 'жахливий', 'en': 'terrible', 'nd': 'vreselijk'},
	{'uk': 'справедливий', 'en': 'fair', 'nd': 'eerlijk'},
	{'uk': 'несправедливий', 'en': 'unfair', 'nd': 'oneerlijk'},
	{'uk': 'нормальний', 'en': 'normal', 'nd': 'normaal'},
	{'uk': 'ненормальний', 'en': 'abnormal', 'nd': 'abnormaal'},
	# {'uk': '', 'en': '', 'nd': ''},
]